/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    // Write the testcase
}
